// File name: USER.h
// Author: Scott Kang
// userid: kangk
// Email: kyung.ho.kang@vanderbilt.edu
// Description: Implementing USER class that is necessary for programming ATM machine
// Last Changed: 2022 06/21

#include <string>

#ifndef ATM_USER_H
#define ATM_USER_H



using namespace std;

// do not necessarily need cpp file and all the methods can be defined in h file
// but divided them for simplicity

class USER{

public :

    //constructors
    USER();
    USER(string firstName, string LastName, int accountNumber, string birthday);

    //did not define a destructor because the one generated by a compiler is good enough

    //copy constructor
    USER(const USER &lhs);

    //assignment operator
    USER& operator=(const USER &lhs);


    //Accessors
    string getFirstName();
    string getLastName();
    int getAccountNumber();
    string getBirthdate();

    //Modifiers
    void setFirstName(string firstName);
    void setLastName(string lastName);
    void setAccountNumber(int accountNumber);
    void setBirthDate(string birthdate);

private :

    string firstName;
    string lastName;
    int accountNumber;
    string birthdate;

};

#endif //ATM_USER_H